name: mitch-site
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Copy submodule assets
        run: cp -r src/pages/val_comp/static/val_images static/val_images

      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify build
        run: ls -la public

      - name: copy file via ssh key to temp
        uses: appleboy/scp-action@master
        with:
          source: "public/*"
          target: "/home/${{ secrets.USER }}/site/temp"
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          strip_components: 1
          rm: true

      - name: sync to permenant directory
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            ${{ secrets.SYNC_SCRIPT }}
            ${{ secrets.CLEANUP_SCRIPT }}